### ISSUE TITLE
Support vertical kern subtables?

### ISSUE THREAD

**Issue by khaledhosny** [khaledhosny/ots#123]
We currently reject kern subtables specifying vertical kerning for no good reason, should we accept them? Might not be worth it give that `kern` table is basically deprecated for OpenType fonts and I doubt there are any fonts that use it for vertical kerning.

**Comment by davelab6** [comment]
I guess that ots should accept them - they are valid afterall - and this
can help legacy East Asian fonts - but this seems very low priority. It
might be nice to give to an intern. Maybe we can organize an outreachy or
gsoc mentoring program...

On Apr 1, 2017 12:09 PM, "Khaled Hosny" <notifications@github.com> wrote:

We currently reject kern subtables specifying vertical kerning for no good
reason, should we accept them? Might not be worth it give that kern table
is basically deprecated for OpenType fonts and I doubt there are any fonts
that use it for vertical kerning.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/khaledhosny/ots/issues/123>, or mute the thread

**Comment by khaledhosny** [comment]
It is just one line of code removal, I’m only filing this to look for some font later.

**Comment by davelab6** [comment]
Lol ok then 😂

**Comment by khaledhosny** [comment]
`kern` table is dead.
