### ISSUE TITLE
Apple glyf table flags bit 6 causes Fatal Error

### ISSUE THREAD

**Issue by Lorp** [khaledhosny/ots#146]
Although it is specified as Reserved by both the Apple and Microsoft glyf table specifications, there are cases of fonts using bit 6 (0x40) of the flags in the glyph table to resolve an issue with overlaps in some versions of the Apple renderer (including the current macOS Sierra).

Currently, OTS rejects fonts with this bit set. I recommend not rejecting these fonts, because we may soon encounter such fonts more often, given that on-demand static instances may be made from variable fonts — which frequently contain overlaps. The bit does indeed solve problems, yet **these fonts cannot be used as webfonts in Chrome or Firefox on macOS due to their built-in OTS**.

@twardoch writes in detail about the use of the bit here:

https://github.com/twardoch/test-fonts/blob/master/varia/160413-EvenOddTT/README.md

… and notes that it is described by Apple here:

https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6AATIntro.html

**Comment by khaledhosny** [comment]
I’d like to fix that, but I think this is a rather spec bug and the spec needs to be fixed as well (if not first).

**Comment by twardoch** [comment]
This is a tricky bit. There are a number of SFNT tables that are shared between OpenType and ISO Open Font Format on one hand and the Apple TrueType spec on the other hand. The glyf table is one such table of course. It's hard to say what exactly is "valid" if both specs diverge. 

https://github.com/twardoch/test-fonts/blob/master/varia/160413-EvenOddTT/README.md documents the problem and shows that this issue is documented in the Apple spec although not in a straightforward way. But it's not just an ad hoc hack.

**Comment by khaledhosny** [comment]
As the document linked above states, both Apple and OpenType `glyf` table specs document this bit as reserved and should be set to zero, but Apple spec contradicts itself in a relatively obscure place. Furthermore the similar composite glyphs bit (bit 10; `OVERLAP_COMPOUND`) is already documented in both specs (with OpenType spec stating “Use of this flag is not required in OpenType”), so something similar can and should be done here. Looks like just an oversight to me.
