### ISSUE TITLE
CFF with empty Blues operators in PrivateDict is rejected

### ISSUE THREAD

**Issue by anthrotype** [khaledhosny/ots#156]
https://github.com/khaledhosny/ots/blob/dcfa05f/src/cff.cc#L378-L385

This issue resurfaced here:
https://github.com/fonttools/fonttools/issues/152#issuecomment-346177567

Originally discussed at:
https://github.com/googlei18n/ufo2ft/pull/115

Khaled comment
> I think it is safer (and quicker) to just not write empty operator than for me to try to guess what the original OTS author(s) had in mind when this check was written, fix it, then wait for the new version of OTS to propagate to the browsers and for significant users to switch to new enough versions. It will probably be several years, at best, before one can rely on this anyway. :)
> But feel free to open an issue against OTS so that we can look into this at some point.

**Comment by miguelsousa** [comment]
Comment from @readroberts:

It is legal to omit everything from a Private Dict, including BlueValues. It is also legal to provide an empty BlueValue array. I quote from the last paragraph of section 5.3 in the Type 1 Spec:

>The BlueValues array is required in the Private dictionary. If no alignment zones are necessary, use an empty array for the value of BlueValues.

**Comment by anthrotype** [comment]
Thanks Read and Miguel!
So.. we should conclude the ots is wrong in rejecting these empty blues arrays.

/cc @khaledhosny @behdad

**Comment by behdad** [comment]
Boy am I surprised...?

**Comment by khaledhosny** [comment]
What about StemSnapH, StemSnapV, StdHW, StdVW, BlueScale, BlueShift, BlueFuzz, etc, can they have empty operands too?

**Comment by readroberts** [comment]
None of the operators can have no operands.  All of the fields with a single numeric value, such as BlueScale, BlueShift, BlueFuzz, can be omitted, as there is a default value which is implied by the absence of the operator. This is all in section 15 of the CFF spec. Of the operators which take a list operand, only BlueValues is required; the others are all optional. This is in section 5.4 of the Type 1 specification. Section 15 of the CFF spec notes that 'The names of the Private DICT operators shown in Table 23 are, where possible, the same as the corresponding Type 1 dict keys', which I believe implies the behavior is the same unless specified otherwise.  There is no statement in either spec  about whether an empty array is legal for any of the BlueValue operators other than 'BlueValues'.  My choice would be to allow an empty array for all the Blue operators, and that this should have the same effect as omitting the operators.

**Comment by khaledhosny** [comment]
Thanks for explanation!
