### ISSUE TITLE
meson fails to find system library woff2 (lack of .pc file)

### ISSUE THREAD

**Issue by Apteryks** [khaledhosny/ots#242]
Hello, 

On my system (GNU Guix), teh woff2 package lacks CMake or pkg-config files, which I suppose distribution such as Debian perhaps patch-in.  I'd suggest using `cxx.find_library(libwoff2dec)` instead, which will also work for distributions not adding these files.

Thank you!

**Comment by khaledhosny** [comment]
If you can make a pull request that would be great, otherwise I’m afraid my meson skills are rudimentary.

**Comment by eli-schwartz** [comment]
This is incorrect for a couple of reasons:
- upstream woff2 provides these pkg-config files, so if guix is not distributing them, this is a guix bug -- Debian is not the only distro that provides them, no one is patching anything in. In fact, upstream woff2 mandates those files be installed, so guix may be patching them *out*
- `libwoff2dec` is a pkg-config name, not a library name, the library is `woff2dec`
- searching for the library is incorrect, because it doesn't detect the library's static dependencies: libwoff2common, libbrotlidec, etc.
- dependency interfaces allow handling subproject fallback, cxx.find_library does not, switching to cc.find_library would either greatly complicate meson.build or regress in functionality

**Comment by khaledhosny** [comment]
I missed the fact that woff2 do provide pkg-config files (it was not obvious from a cursory look at the GitHub repo). Nothing to do here then.

**Comment by Apteryks** [comment]
Hello, and thank you for the prompt resolution, and apologies for not noticing that the woff2 `*.pc` files *were* indeed installed.  I investigated on my side and ended up finding the culprit:

```
$ guix shell --pure pkg-config woff2 -- pkg-config --libs libwoff2dec
Package libbrotlidec was not found in the pkg-config search path.
Perhaps you should add the directory containing `libbrotlidec.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libbrotlidec', required by 'libwoff2dec', not found
```

The fix was to modify the Guix `woff2` package to have `brotli` as a propagated input instead of a regular input.

Thanks again, and sorry for the noise!

**Comment by eli-schwartz** [comment]
> it was not obvious from a cursory look at the GitHub repo

They do it in an exceedingly confusing manner: they have a CMakeLists.txt function to create a pkg-config file by taking every field as string parameters, so it looks like this:
```
generate_pkg_config ("${CMAKE_CURRENT_BINARY_DIR}/libwoff2dec.pc"
  NAME libwoff2dec
  DESCRIPTION "WOFF2 decoder library"
  URL "https://github.com/google/woff2"
  VERSION "${WOFF2_VERSION}"
  DEPENDS libbrotlidec
  DEPENDS_PRIVATE libwoff2common
  LIBRARIES woff2dec)
```

> The fix was to modify the Guix `woff2` package to have `brotli` as a propagated input instead of a regular input.

Alright, happy to help clarify things.

For the record, `builddir/meson-logs/meson-log.txt` contains debug logs of Meson's attempt at pkg-config resolution, which can generally be a good starting point for debugging issues like this. You should find the same error logs about libbrotlidec there.

**Comment by Apteryks** [comment]
> For the record, `builddir/meson-logs/meson-log.txt` contains debug logs of Meson's attempt at pkg-config resolution, which can generally be a good starting point for debugging issues like this. You should find the same error logs about libbrotlidec there.

Thanks for the tip, I'm sure it'll prove useful in the future!  Cheers.
