### ISSUE TITLE
Drop checks for GSUB/GPOS/GDEF

### ISSUE THREAD

**Issue by behdad** [khaledhosny/ots#28]
In layout.cc, this is unnecessary:

````c
  // The spec requires a script table for 'DFLT' tag must contain non-NULL 
  // |offset_default_lang_sys| and |lang_sys_count| == 0 
  if (tag == kScriptTableTagDflt && 
      (offset_default_lang_sys == 0 || lang_sys_count != 0)) { 
    return OTS_FAILURE_MSG("DFLT table doesn't satisfy the spec. in table %4s", (char *)&tag); 
  }
````

**Comment by fred-wang** [comment]
So as I just discussed on IRC with Khaled, GNU Free Font gives a concrete example:

https://www.gnu.org/software/freefont/

(I tested FreeSerif built from SVN revision r3038)

**Comment by behdad** [comment]
Lets start a test suite and gather curated fonts that we want to make sure pass ot-sanitize.  Should be trivial to set up.  Keep the ttx in git and compile on the fly when running test suite...

**Comment by fred-wang** [comment]
Is there any plan to replace the error failures with some way to report warnings instead?

**Comment by behdad** [comment]
Warnings like that really belong into a lint tool...

**Comment by behdad** [comment]
Yet another report:
https://code.google.com/p/chromium/issues/detail?id=490634

Copying what I wrote there:

I think we should *significantly* relax GSUB/GPOS/GDEF in OTS.

For one thing, if in the future we want to use some of the unused lookup flags, add new feature types, etc, we don't want the full table to be dropped when used in older browsers.

Since both Chrome and Firefox always use HarfBuzz for GSUB/GPOS/GDEF processing, I like to suggest passthru-ing those tables.

In the HarfBuzz handling of those tables we found one crasher over the past five years.  I thought, well, maybe here's actually one place that OTS was beneficial in not exposing a possible vulnerability.  But then I checked OTS code and it wasn't catching that problem either.  Since I believe all of us are much more confident in HB code for those tables than the OTS one, I don't see the point in keeping the checks.   It was a different world when we were relying on Uniscribe / CoreText for those tables.

**Comment by behdad** [comment]
CC @jfkthame

**Comment by jfkthame** [comment]
I guess Chrome and Firefox could pass-thru those tables if they like, but I don't think I agree with relaxing or dropping the checks in OTS itself. We should *not* be regarding OTS as solely a component of harfbuzz-based browsers. It's a library/tool in its own right and should be behaving as correctly as possible with regard to the standards it supports (e.g. OpenType 1.7).

If we want to use currently-reserved flags in some future version of OpenType, for example, it's not at all clear that passing these through to all clients, or even to older harfbuzz-using browsers, is a good thing: presumably, an old version of Chrome or Firefox is likely to be using an old version of harfbuzz, which won't understand the newly-defined flags anyway. So dropping the table (with a warning) may be better than silently passing it through and getting behavior quite different from what the font designer intended.

If the client app wants to take a chance on accepting unknown future table versions with new flags, etc., it can do that by explicitly asking OTS to pass the tables unchecked. But I don't think that decision should be baked into OTS itself.

**Comment by jfkthame** [comment]
To continue.... I don't think it's necessarily OTS's job to pass every font that's "out there" unless we have concrete evidence that it's dangerous for rendering systems. I'd start from the opposite standpoint: it's OTS's job to ensure that fonts conform to the published specification, and fix (where possible) or reject (otherwise) those that don't. We may allow individual, carefully-considered exceptions to this *if* it seems clear that there are cases where a particular error is present in widespread/important fonts (yes, that's vague) and is unlikely in practice to lead to problems, but the default should always be to enforce the specification.

In a case like GNU FreeFont (mentioned above), I think the first response should be to report a bug against FreeFont. If it's violating the OT/OFF spec, it should be fixed. The first response should *not* be to tweak OTS so as to let an out-of-spec font through anyway; that should be a last resort if we conclude that there's an important, broken, but harmless font out there that cannot reasonably get fixed.

**Comment by fred-wang** [comment]
> In a case like GNU FreeFont (mentioned above), I think the first response should be to report a bug against FreeFont. If it's violating the OT/OFF spec, it should be fixed.

Just for the record, I've discussed this issue with Stevan White before posting here. However, he seems to have strong feeling against tools like OTS (from his point of view, this is used by browser vendors to reject responsibility of a broken font on the font author, instead of fixing their applications). So he didn't seem very willing to cooperate on this and I didn't insist too much...

**Comment by jfkthame** [comment]
If the font conforms to the spec, and OTS rejects it because it's in some way unusual (yet still spec-conformant), that'd be an entirely different situation, and the font developer should not need to jump through hoops to get their font through the sanitizer; instead, the sanitizer should be fixed.

But if the font doesn't conform to the spec, the font is by definition broken. It may happen to work in some contexts, because not all software systems treat out-of-spec inputs in the same way, but that's basically irrelevant; it's still wrong, and should be fixed.

**Comment by fred-wang** [comment]
@jfkthame: I essentially agree with you here and GNU Free Font should be fixed, but maybe you should write to Stevan White ;-) I also think OTS should definitely warn about non-conformant behavior ; but in this particular case and in a browser context, it might be a bit harsh to reject the whole GSUB table especially given browser's very tolerant behavior with "broken" Web pages.

**Comment by jfkthame** [comment]
Could you clarify exactly what problem you're seeing? I just tried a brief test (with the current release of FreeSerif.otf, from http://ftp.gnu.org/gnu/freefont/), and AFAICS the OpenType tables are accepted by Firefox without problems (e.g. ligatures work as expected). So I'm not sure what I'd report as a "bug"......

**Comment by fred-wang** [comment]
The release is very old, perhaps it's only with the dev version...

On http://fred-wang.github.io/MathFonts/GNUFreeSerif/ I obtain:

downloadable font: Layout: DFLT table doesn't satisfy the spec. for script tag TLFD (font-family: "FreeSerif" style:normal weight:bold stretch:normal src index:0) source: http://fred-wang.github.io/MathFonts/GNUFreeSerif/FreeSerifBold.woff mathfonts.css:14:12
downloadable font: Layout: Failed to parse script table 0 (font-family: "FreeSerif" style:normal weight:bold stretch:normal src index:0) source: http://fred-wang.github.io/MathFonts/GNUFreeSerif/FreeSerifBold.woff mathfonts.css:14:12
downloadable font: GSUB: Failed to parse script list table, table discarded (font-family: "FreeSerif" style:normal weight:bold stretch:normal src index:0) source: http://fred-wang.github.io/MathFonts/GNUFreeSerif/FreeSerifBold.woff mathfonts.css:14:12
downloadable font: name: name records are not sorted. (font-family: "FreeSerif" style:normal weight:normal stretch:normal src index:0) source: http://fred-wang.github.io/MathFonts/GNUFreeSerif/FreeSerif.woff mathfonts.css:10:12
downloadable font: Layout: Bad input count 0 in chain class rule subtable (font-family: "FreeSerif" style:normal weight:normal stretch:normal src index:0) source: http://fred-wang.github.io/MathFonts/GNUFreeSerif/FreeSerif.woff mathfonts.css:10:12
downloadable font: Layout: Failed to parse chain class rule 0 in chain class set (font-family: "FreeSerif" style:normal weight:normal stretch:normal src index:0) source: http://fred-wang.github.io/MathFonts/GNUFreeSerif/FreeSerif.woff mathfonts.css:10:12
downloadable font: Layout: Failed to parse chain class set table 0 in chain context format 2 (font-family: "FreeSerif" style:normal weight:normal stretch:normal src index:0) source: http://fred-wang.github.io/MathFonts/GNUFreeSerif/FreeSerif.woff mathfonts.css:10:12
downloadable font: Layout: Failed to parse chaining context format 2 subtable (font-family: "FreeSerif" style:normal weight:normal stretch:normal src index:0) source: http://fred-wang.github.io/MathFonts/GNUFreeSerif/FreeSerif.woff mathfonts.css:10:12
downloadable font: Layout: Failed to parse lookup subtable 5 (font-family: "FreeSerif" style:normal weight:normal stretch:normal src index:0) source: http://fred-wang.github.io/MathFonts/GNUFreeSerif/FreeSerif.woff mathfonts.css:10:12
downloadable font: Layout: Failed to parse subtable 0 (font-family: "FreeSerif" style:normal weight:normal stretch:normal src index:0) source: http://fred-wang.github.io/MathFonts/GNUFreeSerif/FreeSerif.woff mathfonts.css:10:12
downloadable font: Layout: Failed to parse lookup 22 (font-family: "FreeSerif" style:normal weight:normal stretch:normal src index:0) source: http://fred-wang.github.io/MathFonts/GNUFreeSerif/FreeSerif.woff mathfonts.css:10:12
downloadable font: GSUB: Failed to parse lookup list table, table discarded (font-family: "FreeSerif" style:normal weight:normal stretch:normal src index:0) source: http://fred-wang.github.io/MathFonts/GNUFreeSerif/FreeSerif.woff

**Comment by jfkthame** [comment]
OK, I see errors like that on your test page. But where did you get those fonts? Is there a newer (pre-/beta/...?) release available somewhere?

Or if you built the fonts from source, then it's possible this should be reported as a bug in the font creation tool used (FontForge, I presume).

**Comment by fred-wang** [comment]
These are built from the SVN repository of GNU Free Font (and Stevan said he wanted to do a new release in the upcoming months BTW):

http://savannah.gnu.org/svn/?group=freefont

The "make woff" command will produce WOFF fonts. Reading the source, these are created with the help of FontForge.

**Comment by behdad** [comment]
Another example:
https://code.google.com/p/chromium/issues/detail?id=490634

I'll reply to Jonathan's comments in detail later today.

**Comment by jfkthame** [comment]
> The "make woff" command will produce WOFF fonts. Reading the source, these are created with the
> help of FontForge.

So this could very well be a bug in fontforge, or more precisely in the version you happened to use. ISTM a deeper investigation is needed before we can determine for sure where the bug should be reported; and I'd be against changing OTS to just ignore the errors, at least until that due diligence has been done and we understand the situation more fully.

> Another example:
> https://code.google.com/p/chromium/issues/detail?id=490634

Are the OTS error reports (see comment 5 there) accurate? In particular, if

> ERROR: GDEF: Invalid offset to glyph classes, table discarded

is correct (I haven't tried to actually debug the font), then I suspect this leads to the subsequent GSUB errors, because the GDEF is discarded and therefore glyph classes are not available.

Arguable, perhaps we could make OTS a bit more tolerant, so that if the GDEF is missing (or invalid/dropped), it would only discard the individual lookups that require GDEF tables rather than dropping the entire GSUB table. But in practice I doubt this would help much; if the GDEF is unusable then lookups that depend on mark classes, etc., are not going to work as intended, and we might as well make the brokenness really clear.

**Comment by khaledhosny** [comment]
Chrome now passes these tables thru on its own, so closing this.
