### ISSUE TITLE
OTS fails to parse GDEF table with empty ClassDef

### ISSUE THREAD

**Issue by PeterDekkers** [khaledhosny/ots#282]
Hello! When the `GDEF` table contains an empty class—fontTools [ClassDef](https://github.com/fonttools/fonttools/blob/770917d89e9151023cce011c7f7223f4ce84169e/Lib/fontTools/ttLib/tables/otTables.py#L1332) without `classDefs`—, OTS `9.1.0` fails to parse the table with:
```shell
ERROR: GDEF: Invalid offset to glyph classes
ERROR: GDEF: Failed to parse table
Failed to sanitize file!
```

The `GDEF` table looks like this, with the issue here being that `MarkAttachClassDef` doesn't have any `ClassDef` entries—it's empty.
![Screenshot 2024-08-26 at 20 12 14](https://github.com/user-attachments/assets/573aeb02-2cd7-4787-9b68-47394de2a8a7)

The part of the OTS code that triggers the error is here:
https://github.com/khaledhosny/ots/blob/27d63ae4d8988619e0a661bf40551c47da47f3fa/src/gdef.cc#L283C1-L286C6

This seems like an error in OTS' parsing of the `GDEF` table, possibly. Please let me know if I can provide any further information. Thanks :)

**Comment by jfkthame** [comment]
@PeterDekkers  Could you attach an example font that exhibits this failure, so we can see the actual binary form of the GDEF table? Thanks.

**Comment by PeterDekkers** [comment]
@jfkthame sure. 

FYI, the only files I can provide are subject to font licensing, so please use them only for your testing. Thank you for understanding. Also, this TTF file was built with the [Adobe Font Development Kit for OpenType](https://github.com/adobe-type-tools/afdko), for reference.

[gdef-empty-class-test-file.zip](https://github.com/user-attachments/files/16770754/gdef-empty-class-test-file.zip)

**Comment by khaledhosny** [comment]
The GDEF table has a `glyphClassDefOffset` of 10, and a `markAttachClassDefOffset` of 2, but the table header is 12 bytes (version 1.0), so the offsets point inside of to the table header and while this is technically valid, we intentionally don’t allow such data overlap.

Even if we accept these offsets, the mark attachment class definition table has a `format` of to 0 which is invalid (only formats 1 and 2 are defined), which indicates that these offsets are incorrectly set.

I don’t think there is a big here, we are rightfully rejecting a broken GDEF table.

**Comment by jfkthame** [comment]
Agreed; the GDEF is broken and OTS is correct to reject it. It looks like the Glyph Class Definition table has been written two bytes too early, overwriting the end of the GDEF header and stomping on the `markAttachClassDefOffset` field.

(Initially I was guessing that the `markAttachClassDefOffset` would be pointing to the very end of the GDEF table, implying it had zero length -- which would also be invalid, but potentially could be patched up by just zeroing the offset in the header. But things are worse than that. There are enough trailing zero bytes in the table for an empty Mark Attachment Class Definition table to be present, but (a) it doesn't have a valid format identifier, and (b) the offset in the header doesn't point there, because it was overwritten by the start of the Glyph Class Definition table.)

So if this font was generated by the AFDKO (and not subsequently processed in any way), this looks like a bug that should be reported to Adobe.

**Comment by PeterDekkers** [comment]
Thank you so much for taking a look, and for the detailed replies, @khaledhosny and @jfkthame.

At the end of the day, the `GDEF` table is also easily corrected (e.g. with `fontTools`), which is what we are currently doing.

**Comment by jfkthame** [comment]
OK, good to know that serves as a workaround. It'd still be worth reporting the issue at https://github.com/adobe-type-tools/afdko/issues, I think, especially if you can provide a minimal example of AFDKO input that creates a faulty GDEF table.
