### ISSUE TITLE
Cmap platform 0 encoding 1 is rejected

### ISSUE THREAD

**Issue by behdad** [khaledhosny/ots#34]
It should work just like 0.0

**Comment by YellowYak** [comment]
Has this fix been implemented by Firefox and Chrome? I ask because when using pdf.js to load a PDF document with the embedded Helvetica Neue font I get a substitution font and artifacts, as noted by sairuspatel back almost a year ago.

I posted an issue to pdf.js, https://github.com/mozilla/pdf.js/issues/6343, in which I have a PDF document that when viewed through https://mozilla.github.io/pdf.js/web/viewer.html renders the Helvetica Neue font correctly in Internet Explorer 11, but not in Firefox 39 or Chrome 44.

What version of OTS is being used by the latest versions of FF and Chrome? Are they using a version that includes the fix here?

Thanks

**Comment by khaledhosny** [comment]
This was fixed last year, so I suppose Chrome and Firefox got it by now, but you can check the source code of both to see what version of OTS they are using.
