### ISSUE TITLE
pthread error when making in CentOS

### ISSUE THREAD

**Issue by SatheeshJM** [khaledhosny/ots#46]
I am using CentOS. 
When I call make(after following the previous steps), after a point I get this error..

```
LINK(target) out/Default/cff_type2_charstring_test
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../libgtest.so: undefined reference to `pthread_key_create'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../libgtest.so: undefined reference to `pthread_getspecific'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../libgtest.so: undefined reference to `pthread_key_delete'
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../libgtest.so: undefined reference to `pthread_setspecific'
collect2: ld returned 1 exit status
make: *** [out/Default/cff_type2_charstring_test] Error 1
```

What is the problem here?

**Comment by khaledhosny** [comment]
We are not using gtest in the recommended way (copying it to our project and statically linking it IIRC), so it is not reliable. I haven’t done that yet because I’m not that familiar with gyp build system to easily extend it, any help here is appreciated.

 However, we only use gtest for some tests, so if you are only interested in the `ot-sanitise` utility you can specifically run `make ot-sanitise` as it does not use gtest. If you just want `libots` then you don’t need to build anything in the `test` directly.

**Comment by SatheeshJM** [comment]
Ah!  Thanks. 
In do need just the ot-sanitise so I called `make ot-sanitise`.. It builds without any error.. 
So far so good. 

How do I invoke the library now though? 
I call .`/ot-sanitise font.ttf` as mentioned [here](https://github.com/khaledhosny/ots/blob/master/test/README). But it just says No such file or directory

**Comment by khaledhosny** [comment]
The built binaries should be under `out/Default/`.

**Comment by SatheeshJM** [comment]
Great! Thanks a lot!
