### ISSUE TITLE
--version

### ISSUE THREAD

**Issue by davelab6** [khaledhosny/ots#61]
It would be helpful to have a `--version` arg :)

**Comment by behdad** [comment]
Possibly also, if there are any error / warnings being produced, send a message with version (which I suppose will be git hash or something).

**Comment by khaledhosny** [comment]
We don’t have releases nor versions so far. We can use `PACKAGE_VERSION` from autottols build, but that wouldn’t work if you don’t use the autotools build (i.e. everyone). Using git hash is interesting idea, but we will still need to set it manually since no one is building directly from our git tree, so we need to make releases anyway.

**Comment by davelab6** [comment]
What do you need to do to cut a release? :)

**Comment by khaledhosny** [comment]
No idea actually, that is why I don’t make any.

**Comment by behdad** [comment]
Just every time you fix a major bug, tag it with a number.  That's good enough.

**Comment by davelab6** [comment]
Semver.org style :)
