### ISSUE TITLE
Reject font if any of GDEF/GSUB/GPOS is being dropped

### ISSUE THREAD

**Issue by behdad** [khaledhosny/ots#74]
Dropping GDEF/GSUB/GPOS from font and acting as if everything is fine is not good.  If OTS is rejecting those tables, then it should reject the font.  Otherwise it creates obscure bugs that need to be tracked down because the font seems to kinda work but not fully...

[I'm personally of the opinion that OTS shouldn't touch those tables as HarfBuzz knows how to deal with them, but that's a separate issue.]

**Comment by behdad** [comment]
cc @jfkthame

**Comment by khaledhosny** [comment]
I think that makes sense.

**Comment by khaledhosny** [comment]
@jfkthame are you OK with this?

**Comment by jfkthame** [comment]
Yes, I think I'm OK with rejecting the font if these tables are bad. I suppose the original design here was thinking in terms of things like Latin, where dropping ligatures and kerning (for example) still leaves a functional -- if typographically inferior -- font. But for many writing systems, dropping the OT Layout tables will result in a font that is fundamentally broken and cannot render legible text. Better to reject it outright and let the client decide what to do (find a different font, usually).

**Comment by twardoch** [comment]
I shall add that from the perspective of a font tool maker (FontLab), I think I prefer if bugs manifest themselves loud rather than semi-silently. The permissiveness of various inconsistencies within SFNT (due to the long evolution of the format) is only superfcially beneficial. In reality, this tolerance for bugs hurts the industry rather than helps it — the bugs amass and there is not enough pressure to fix them. 

When OTS first came around, I hated its guts because it caused me more work. But I see now that in the longer run, it saves me work, because buggy code *had been* finally fixed. So I welcome this direction, and in fact I won't mind if OTS becomes slightly more restrictive over time. 

Of course the real problem will potentially be false alarms raised by OTS, but the library has evolved long so it is now a more reliable gatekeeper.

**Comment by davelab6** [comment]
I agree with Adam, this is causing me more work as there are 14 families in
the Google Fonts collection that need to be fixed urgently, as Firefox 44
is released on January 26 and uses a version of OTS that will stop
displaying fonts, but these fonts should have been fixed already :)

**Comment by davelab6** [comment]
Also, @khaledhosny mentioned in a chat that if one compiles OTS with

    make CXXFLAGS=-DOTS_DEBUG

then it reports the source code lines related to the error, eg

```
$ ./ot-sanitise ~/fonts/ofl/merriweathersans/MerriweatherSans-Bold.ttf 
ERROR at src/layout.cc:100 (ParseScriptTable)
ERROR: Layout: DFLT table doesn't satisfy the spec. for script tag DFLT
ERROR at src/layout.cc:1247 (ParseScriptListTable)
ERROR: Layout: Failed to parse script table 0
ERROR at src/gsub.cc:642 (ots_gsub_parse)
ERROR: GSUB: Failed to parse script list table
ERROR at src/ots.cc:669 (ProcessGeneric)
Failed to sanitise file!
```
