### ISSUE TITLE
OTS rejects Unicode LastResort font

### ISSUE THREAD

**Issue by irori** [khaledhosny/ots#80]
https://code.google.com/p/chromium/issues/detail?id=527165

OTS allows up to 65535 groups in cmap table, but the Unicode LastResort font (http://www.unicode.org/policies/lastresortfont_eula.html?utm_source=tuicool) has 387471 groups, in order to map many characters to single glyph.

I'm not sure if we should support such an extreme case.

**Comment by khaledhosny** [comment]
I think this comment in `cmap.cc` is dubious:
````
// The maximum number of groups in format 12, 13 or 14 subtables.
// Note: 0xFFFF is the maximum number of glyphs in a single font file.
const unsigned kMaxCMAPGroups = 0xFFFF;
````
There is no relation between the number of possible glyphs in the font and the number of characters it can support, as evidenced by this font.

But even after dropping all uses of this constant, the font is still rejected because it has entries for surrogate pairs, and I'm not sure if it is correct to map surrogate pairs to glyphs.

**Comment by khaledhosny** [comment]
See also #77 for the case in favour of restricting the allowed number of cmap groups.

**Comment by behdad** [comment]
I don't think we should reject fonts that have mappings for surrogate pairs.  That's just OTS getting in the way too much.

**Comment by khaledhosny** [comment]
I tend to agree. If someone can send a batch to remove this limitation (as well as address your comment on #77) I’ll take it, otherwise I’ll give it a try when I have time.
