### ISSUE TITLE
Update OTS to match Freetype2 2.6.3 CFF supported opcodes

### ISSUE THREAD

**Issue by Pomax** [khaledhosny/ots#97]
[Freetype2 2.6.3 now supports all CFF opcodes except for `random`](https://sourceforge.net/projects/freetype/files/freetype2/2.6.3/), which means OTS should probably no longer throw errors when it sees any CFF opcode in a charstring that isn't `random`, too.

For convenience, I've compiled a set of CFF fonts that make use of each of the non-pathing opcodes supported by Freetype2 2.6.3, with the assumption that the `gsubr` and `subr` opcodes are already supported: https://github.com/Pomax/cff-opcode-fonts

**Comment by HinTak** [comment]
It may be better simply to insert hooks into FreeType where it encounters an unknown CFF opcode, and, instead of silently works around it and/or ignoring it, emit a message saying so.

That has a number of advantages: your sanitizer always agree with the font engine where a problem is - although one says visibly there is a problem, the other works around and silently ignore problems.

There are also a number of disadvantages: you are stuck with a patched freetype (some extra code is upsteam'able, some not, especially when it slows down freetype), and also you will get all the bugs from freetype too; so an "independent" validation may be desired.

One may say a patched freetype (away from the system one) is an advantage - for MS FontVal, it is - I don't worry about breaking my display.

For the (truetype) rasterization test in MS FontVal, exposing all the places where Freetype silently works around hinting problems into visible messages was what make 2.0 possible and nearly identical functionality with 1.0, within about 2 weeks' work. Sticking with a patched freetype wasn't a big issue either, since FontVal's users are mostly Mac, then windows, with Linux users being very much a minority (me, one!...).

If I ever implement a rasterization test for CFF in FontVal, I'd either draw on FreeType further or bring in some related C code from AFDKO, instead of writing it new. But that's my decision.

If you are going to draw on FreeType, there is a chance I'd borrow that code too :-).

**Comment by HinTak** [comment]
I see "bring in some related C code from AFDKO," wasn't given enough emphasis...

**Comment by khaledhosny** [comment]
Same as for #83 and #84.
